<Project Sdk="Microsoft.NET.Sdk">

<PropertyGroup>
  <OutputType>WinExe</OutputType>
  <TargetFramework>net46</TargetFramework>
  <LangVersion>latest</LangVersion>
  <Nullable>enable</Nullable>

  <GenerateSupportedRuntime>false</GenerateSupportedRuntime>
  <PublishRelease>true</PublishRelease>

  <Deterministic>true</Deterministic>
  <InvariantGlobalization>true</InvariantGlobalization>
  <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  <DebugType Condition="'$(Configuration)' == 'Release'">none</DebugType>
  <OutputPath>bin</OutputPath>
  <PublishDir>bin</PublishDir>
  <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
</PropertyGroup>

</Project>